name: Build and Push Debian

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'docker.io/lrwx/debian/**'
      - '.github/workflows/docker-io-lrwx-debian.yml'
  pull_request:
    paths:
      - 'docker.io/lrwx/debian/**'
      - '.github/workflows/docker-io-lrwx-debian.yml'
  workflow_dispatch:
    inputs:
      DEBIAN_RELEASE:
        description: 'Upstream release tag'
        required: false
        default: 'latest'
        type: string
      TZ:
        description: 'Timezone (TZ)'
        required: false
        default: 'Asia/Shanghai'
        type: choice
        options:
          - 'Asia/Shanghai'
          - 'UTC'
          - 'America/Los_Angeles'
          - 'America/New_York'
      APT_MIRROR:
        description: 'APT mirror'
        required: false
        default: 'deb.debian.org'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Set up multiarch support
        uses: docker/setup-qemu-action@v4

      - name: Set up container builder
        uses: docker/setup-buildx-action@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: lrwx/debian
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{commit_date 'YYYYMMDDHHmmssZZ' tz='${{ github.event.inputs.TZ || 'Asia/Shanghai' }}'}}

      - name: Build and push container image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./docker.io/lrwx/debian/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            DEBIAN_RELEASE=${{ github.event.inputs.DEBIAN_RELEASE || 'latest' }}
            TZ=${{ github.event.inputs.TZ || 'Asia/Shanghai' }}
            APT_MIRROR=${{ github.event.inputs.APT_MIRROR || 'deb.debian.org' }}
            DEBIAN_FRONTEND=noninteractive
          cache-from: type=gha
          cache-to: type=gha,mode=max
